schema_version: 1

context:
  name: asyncio-throttle
  version: 1.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/asyncio-throttle-${{ version }}.tar.gz
  sha256: 2675282e99d9129ecc446f917e174bc205c65e36c602aa18603b4948567fcbd4

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - asyncio_throttle
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Simple, easy-to-use throttler for asyncio
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/hallazzang/asyncio-throttle

extra:
  recipe-maintainers:
    - pavelzw
